#!/bin/sh
set -e

cd "$(dirname "$0")/.."

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

ACTIVATE="$VENV_NAME/bin/activate"
if [ ! -f "$ACTIVATE" ]; then
    echo "$ACTIVATE does not exist, run ./script/bootstrap" >&2
    exit 1
fi
. "$ACTIVATE"

SOURCE_DIR="octodns_bind/"

# Don't allow disabling coverage
grep -r -I --line-number "# pragma: +no.*cover" $SOURCE_DIR && {
  echo "Code coverage should not be disabled"
  exit 1
}

# TODO: ensure any common env var secrets have been cleared
export TODO_ACCESS_KEY_ID=

export PYTHONPATH=.:$PYTHONPATH

pytest \
  --disable-network \
  --cov-reset \
  --cov=$SOURCE_DIR \
  --cov-fail-under=100 \
  --cov-report=html \
  --cov-report=xml \
  --cov-report=term \
  --cov-branch \
  "$@"
