#!/bin/bash

# Get current script path
SCRIPT_PATH="$( dirname -- "$( readlink -f -- "${0}"; )"; )"
# Activate OctoDNS Python venv
source "${SCRIPT_PATH}/common.sh"

export BIND_KEY_NAME=
export BIND_KEY_SECRET=

pytest --disable-network "$@"
